Upgrade to JUnit 5.12.1
This commit also adds 'org.junit.platform:junit-platform-launcher' to avoid the following failure:

org.junit.platform.commons.JUnitException: OutputDirectoryProvider not available; probably due to unaligned versions of the junit-platform-engine and junit-platform-launcher jars on the classpath/module path.